spring:
  application:
    name: eureka-server

server:
  port: 9000

eureka:
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false
